name: MailMe
version: 1.5.12
main: com.haroldstudios.mailme.MailMe
api-version: 1.14
authors: [Harolds]
description: Transfer Mail across the virtual galaxy
website: https://wiki.haroldstudios.com
loadbefore:
  - Essentials
  - EssentialsX
softdepend:
  - PlaceholderAPI
  - Vault
  - Multiverse
  - HolographicDisplays

# Required to override essentials /mail
commands:
  mail:
    description: Override command for essentials
    usage: /<command>

permissions:
  mailbox:
    use:
      default: true
    add:
      default: true
    remove:
      default: true
  mailme:
    compose:
      default: true
    inbox:
      default: true
    send:
      item:
        default: true
      letter:
        default: true
      book:
        default: true
  postoffice.use:
    default: true